# ADS NumPy Exercises

In [2]:
conda install numpy

Note: you may need to restart the kernel to use updated packages.
Solving environment: ...working... done


# All requested packages already installed.



In [3]:
import numpy as np

In [4]:
x = [0,1,2,3,4,5,6,7,8,9]
nums = np.array([0,1,2,3,4,5,6,7,8,9])
print(nums)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
nums.shape

(10,)

In [6]:
nums.dtype

dtype('int32')

#Create an array of 10 zeros

In [7]:
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
y = [0.,0.,0.,0.,0.,0.,0.,0.,0.,0.]
array = np.array([0.,0.,0.,0.,0.,0.,0.,0.,0.,0.])
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#Create an array of 10 ones

In [9]:
twodim = np.array([[1,1,1,1,1],[1,1,1,1,1]])
twodim

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [15]:
ones = np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [34]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [36]:
fives = ([[5,5,5,5,5],[5,5,5,5,5,5]])

fives = np.array([[5,5,5,5,5],[5,5,5,5,5,5]]) 
fives = nums.reshape ([[5,5,5,5,5],[5,5,5,5,5,5]])
print(fives)

<ipython-input-36-e09fb9a6f25e>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  fives = np.array([[5,5,5,5,5],[5,5,5,5,5,5]])


TypeError: 'list' object cannot be interpreted as an integer

Create an array of the integers from 10 to 50

In [12]:
twodim = np.arange(10, 51)
twodim

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

Create an array of all the even integers from 10 to 50

In [13]:
twodim = np.arange(10, 52, 2)
twodim

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

Create a 3x3 matrix with values ranging from 0 to 8

In [16]:
array = ([[0, 1, 2],[3, 4, 5]])
array

[[0, 1, 2], [3, 4, 5]]

array = nums.reshape(1, 1)
array 

In [17]:
twodim = np.array ([[0, 1, 2],[3, 4, 5],[6, 7, 8]])
twodim

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Create a 3x3 identity matrix

In [18]:
identity = np.eye(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Use NumPy to generate a random number between 0 and 1

In [32]:
random = np.random.randint(0, 2)
random

1