# ADS NumPy Exercises

In [1]:
conda install numpy

Solving environment: ...working... done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
x = [0,1,2,3,4,5,6,7,8,9]
nums = np.array([0,1,2,3,4,5,6,7,8,9])
print(nums)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
nums.shape

(10,)

In [5]:
nums.dtype

dtype('int32')

#Create an array of 10 zeros

In [6]:
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
y = [0.,0.,0.,0.,0.,0.,0.,0.,0.,0.]
array = np.array([0.,0.,0.,0.,0.,0.,0.,0.,0.,0.])
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#Create an array of 10 ones

In [8]:
twodim = np.array([[1,1,1,1,1],[1,1,1,1,1]])
twodim

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [9]:
ones = np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

##Create an array of 10 fives

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

In [29]:
fives = np.array([[[5,5,5,5,5],[5,5,5,5,5,5],[5,5,5,5,5,5],[5,5,5,5,5,5]]]), 

fives1

<ipython-input-29-a56eca95d4c6>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  fives = np.array([[[5,5,5,5,5],[5,5,5,5,5,5],[5,5,5,5,5,5],[5,5,5,5,5,5]]]),


array([[list([5, 5, 5, 5, 5]), list([5, 5, 5, 5, 5, 5])],
       [list([5, 5, 5, 5, 5, 5]), list([5, 5, 5, 5, 5, 5])]], dtype=object)

Create an array of the integers from 10 to 50

In [11]:
twodim = np.arange(10, 51)
twodim

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

Create an array of all the even integers from 10 to 50

In [15]:
twodim = np.arange(10, 52, 2)
twodim

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

Create a 3x3 matrix with values ranging from 0 to 8

array = np.arange(1, 9)
array

array = ([[0, 1, 2],[3, 4, 5], [6, 7, 8]])

array

nums = nums.reshape (3, 3)
nums

In [35]:
nums2d = np.array(([1,2,3],[4,5,6],[7,8,9]))
nums2d 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array = nums.reshape(1, 1)
array 

In [17]:
twodim = np.array ([[0, 1, 2],[3, 4, 5],[6, 7, 8]])
twodim

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Create a 3x3 identity matrix

In [18]:
identity = np.eye(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Use NumPy to generate a random number between 0 and 1

In [21]:
random = np.random.randint(0, 2)
random

0

In [ ]:
##Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [47]:
stan_norm_dist = np.random.normal (0, 1, 25)
print(stan_norm_dist)


[-0.61822861 -0.22342956  0.67129722 -0.78590504 -0.54505183  1.6969775
  1.93305329 -1.12904112 -0.57801419  0.47115872 -0.48338351 -0.56160527
 -0.06676062 -0.77482417  0.82384933 -0.69293758 -0.38564923  1.53929814
 -0.61289714  0.60674302  1.64892427  0.91917867  0.60444954 -0.75632438
 -0.46882815]


In [31]:
stan_dist1 = np.random.randn(5, 20)
stan_dist1

array([[ 1.04237957,  0.67556743,  0.06200039,  0.21563986,  0.6635188 ,
        -0.35912485, -0.54763595,  2.56694835, -3.05133737,  1.76096866,
        -1.07571235,  0.49648728,  1.1532986 ,  1.87661288, -1.55920638,
         1.48489785,  0.60766091,  1.44659113, -0.533324  ,  0.03991772],
       [ 0.06807206, -0.7202598 , -1.0483258 ,  1.14810123,  0.86094292,
         1.0530573 , -0.2133967 , -1.23480879, -0.42360097, -0.19400215,
         0.56410061, -0.21989307,  0.5734485 ,  0.52196638, -0.59980464,
         0.12474546, -1.18262246,  0.75402016, -0.60713858, -1.08704827],
       [-0.37538046, -0.13480058,  0.06494332, -0.37423711, -0.08348053,
        -0.78930098,  1.36143085, -0.22962239,  1.15333484, -0.70181862,
        -1.57357253,  0.40435251, -1.72843571,  0.56227011, -0.7749527 ,
        -0.56662501, -1.87672921,  0.66285308, -0.15028639,  0.09130202],
       [-0.27265627, -0.088296  , -1.49885515, -0.43955421,  0.43463118,
        -0.84862142, -1.14447527, -0.97360869,  

In [53]:
stan_dist = np.random.rand(5, 20)
stan_dist

array([[0.15374132, 0.99828975, 0.06321501, 0.03154433, 0.57730629,
        0.6911074 , 0.43225864, 0.77390066, 0.55887411, 0.5773845 ,
        0.05520117, 0.10654331, 0.83550556, 0.42634196, 0.82238935,
        0.01363128, 0.57655349, 0.72557842, 0.59090016, 0.01917337],
       [0.94247798, 0.64667016, 0.69753897, 0.5049362 , 0.57255453,
        0.08565601, 0.98996874, 0.41682863, 0.63216412, 0.01571756,
        0.33544972, 0.75732331, 0.38577033, 0.86992621, 0.78496217,
        0.5515032 , 0.28994606, 0.25250196, 0.54021475, 0.24310069],
       [0.80995627, 0.56647799, 0.27883678, 0.33832481, 0.42511304,
        0.77221471, 0.22089911, 0.37252008, 0.28215106, 0.48687533,
        0.29893599, 0.56469585, 0.30146943, 0.2843468 , 0.48338481,
        0.13323291, 0.87452186, 0.45463424, 0.20487313, 0.90985101],
       [0.95301774, 0.29351872, 0.86075022, 0.8439565 , 0.26874546,
        0.36218984, 0.10342679, 0.1427921 , 0.23459154, 0.96715376,
        0.96904718, 0.21212952, 0.32392103, 0

In [ ]:
#Create an array of 20 linearly spaced points between 0 and 1:

In [55]:
linear_sp = np.linspace(0, 1, 20)
linear_sp

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

# Numpy Indexing and Selection

In [95]:
inde_sel = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,])

inde_sel


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [97]:
inde_sel = np.array([[ 1,  2,  3,  4,  5],[6,  7,  8,  9, 10,],[11, 12, 13, 14, 15],
                     [16, 17, 18, 19, 20],[21, 22, 23, 24, 25]])
inde_sel

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [122]:
index = np.arange(11, 26)
index1 = index.reshape(3, 5)
index1
index1 = index[np.mod(np.arange(index.size),5) != 0]
Ans = index1.reshape(3, 4)
Ans

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW AS AN ARRAY

In [44]:
index = np.arange(15, 26)
index
print(20)

20


In [51]:
index = np.arange(1, 14)
index

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [71]:
index1 = index[np.mod(np.arange(index.size),5) != 0]
index1

array([ 2,  3,  4,  5,  7,  8,  9, 10, 12, 13])

In [88]:
np.vstack((index1[0],index1[4],index1[8]))


array([[ 2],
       [ 7],
       [12]])

In [106]:
inde_sel = np.array([[ 1,  2,  3,  4,  5],[6,  7,  8,  9, 10,],[11, 12, 13, 14, 15],
                     [16, 17, 18, 19, 20],[21, 22, 23, 24, 25]])
inde_sel

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [110]:

inde_sel2d = np.array([[ 1,  2,  3,  4,  5],[6,  7,  8,  9, 10,],[11, 12, 13, 14, 15],
                     [16, 17, 18, 19, 20],[21, 22, 23, 24, 25]])
inde_sel2d


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [113]:
inde_sel2d[4,4]

25

In [115]:
print(inde_sel2d[4])

[21 22 23 24 25]


In [133]:
inde_sel3d = np.array([[ 1,  2,  3,  4,  5],[6,  7,  8,  9, 10,],[11, 12, 13, 14, 15],
                     [16, 17, 18, 19, 20],[21, 22, 23, 24, 25]])
inde_sel3d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [134]:
print(inde_sel3d[3], inde_sel3d[4])

[16 17 18 19 20] [21 22 23 24 25]


In [135]:
np.vstack((inde_sel3d[3], inde_sel3d[4]))

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [132]:
inde_sel3 = np.array([[16, 17, 18, 19, 20],[21, 22, 23, 24, 25]])
inde_sel3

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## Now do the following

###Get the sum of all the values in mat

In [101]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])